--- 
abstract: Ensure your Catalyst component isa Moose::Object
author: 
  - Hans Dieter Pearcey <hdp@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.003
license: perl
name: CatalystX-MooseComponent
requires: 
  Catalyst::Runtime: 0
  Moose: 0.70
version: 0.001
